### ISSUE TITLE
Actively enable std modules and/or builtin functions

### ISSUE THREAD

**Issue by earncef** [d5/tengo#119]
What do you think of allowing active enabling of std modules and builtin functions instead of disabling them one by one. That is, in addition to `DisableBuiltinFunction` and `DisableStdModule` also include `EnableBuiltinFunction`, `EnableStdModule`, `DisableAllBuiltins` and `DisableAllStdModules`.

This leaves current usage as is, but also allows disabling all builtins and std modules so that they can be enabled one by one. This is the more secure option that avoids the scenario where an update of tengo automatically updates any possible builtins or modules that need to be locked out in the code the embeds tengo.

**Comment by d5** [comment]
What about adding `SetBuiltinFunctions(map[string]*objects.BuiltinFunction)` and `SetStdModules(map[string]*objects.ImmutableMap)` that replaces all builtins and modules? If we do that, another change we will need is to have VM to take the built functions as a parameter like [builtinModules](https://github.com/d5/tengo/blob/master/runtime/vm.go#L50). Btw, I was using stdmodules and builtin modules in different code but they're the same, which can be confusing. So we may want to fix that too. I'm more inclined towards builtin modules over stdmodules, but, what do you think?

**Comment by earncef** [comment]
`SetBuiltinFunctions` and `SetStdModules` works. It's also consistent with `SetUserModuleLoader`. 

I'm partial towards builtin over std as well and making them consistent is a good idea.
