### ISSUE TITLE
what the relationship between tengo and qlang?

### ISSUE THREAD

**Issue by chenqinghe** [d5/tengo#12]
there is an another script language named [qlang](https://github.com/qiniu/qlang) developed by qiniu. And both the syntax and implementations are similer, so my question is, what is the difference between these two language?

**Comment by d5** [comment]
Haven't seen it before, but, I will check it out. If qlang is also bytecode compiled stack-based VM, the design should be similar? I mean not just these two, but, I'm sure there are other VM implementations out there that have similar design written in many different languages. Btw, I cannot read Chinese, it looks they have implemented a lot of things in it already over 3+ years. Tengo started like 3-4 weeks ago as one of my side projects. :stuck_out_tongue:

**Comment by stefanos82** [comment]
Wait...what?! In such a short period of time you created this beauty? Mad respect to you @d5 :100:
