### ISSUE TITLE
native implementation for increment/decrement statement

### ISSUE THREAD

**Issue by d5** [d5/tengo#136]
currently it's compiled as compound assignment, but, it can be more efficiently implemented in VM

**Comment by ozanh** [comment]
@d5  I tried to implement it to see if there is a gain. I failed. Benchmarks are not better. Patch file is attached. I removed `OpConstant` for `token.Inc` and `token.Dec`, at least I could try this (I am not a pro!).
VM tests passed with this patch but no gain. I tried alternative ways but still same, I think omitting `OpConstant` does not make sense.
Could you please review this [incdec.patch.txt](https://github.com/d5/tengo/files/4636500/incdec.patch.txt) ?

**Comment by d5** [comment]
Sorry, I should have left more detailed note here. The idea was to experiment with a new dedicated opcode for inc/dec statement with some optimized implementation in VM. I haven't tried it myself, but I think we might be able to save some push/pop and instructions that way.

**Comment by geseq** [comment]
Sorry, I should have put a note in here about this. I tried this ages ago and didn’t find much improvement with a separate opcode for inc/dec. What I found was that any gain in performance in incrementing/decrementing was offset by the overall loss in performing the switch with an extra case within the vm loop.

**Comment by ozanh** [comment]
I thought about adding a new opcode but I could not avoid GETL GETG SETL SETG so the quick win seems to use the same BINARYOP switch case.

**Comment by d5** [comment]
😄 well. Looks like we can close this issue now then! Haha.
