### ISSUE TITLE
Interrupt infinite loop

### ISSUE THREAD

**Issue by phenrigomes** [d5/tengo#156]
First, congratulations for Tengo! 

Hey guys! How can I interrupt a loop to avoid bad scripts to run in the host? I searched some example but I could not find.

**Comment by d5** [comment]
You can set the timeout for the VM execution via [Script.RunContext](https://godoc.org/github.com/d5/tengo/script#Script.RunContext) or [Compiled.RunContext](https://godoc.org/github.com/d5/tengo/script#Compiled.RunContext). 

```golang
ctx, cancel := context.WithTimeout(context.Background(), timeout)
defer cancel()

if err := compiled.RunContext(ctx); err != nil {
	panic(err)
}
```
