### ISSUE TITLE
allow execution to be interrupted

### ISSUE THREAD

**Issue by ripienaar** [d5/tengo#17]
This looks great, been looking for something to do some embedded scripting with and this appears to be the best so far - outside of the lua's which i am not a fan of - well done, cannot believe this is a few weeks of work!

When running embedded scripts there's a real risk that they would get stuck forever - maybe someone exec's something that is blocking. 

So would be great if there was a `Run()` or `Script()` that had context support to set deadlines for example.  Be interesting to see how we handle spawned things to avoid zombies in that case though.

**Comment by d5** [comment]
Although `Script` does not directly support it, the runtime has `VM.Abort()` function already. (And that's what I use in the [Playground](https://tengolang.com).) 

If we add something like `script.Compiled.Abort()` _(which should be fairly easy)_, then you should be able to interrupt the execution (likely from another goroutine).

**Comment by ripienaar** [comment]
@d5 nice, yeah then making `ScriptContext` or `RunContext` should be easy enough (same way as exec.CommandContext is used)

**Comment by ripienaar** [comment]
A quick way to implement this:

```
func (c *Compiled) RunContext(ctx context.Context) (err error) {
  done := make(chan struct{}, 1)

  watcher := func() {
    select {
    case <-done:
    case <-ctx.Done():
      c.machine.Abort()
    }
  }

  go watcher()
  defer func() {done <- struct{}{}}()

  return c.Run()
}
```

Also I note since you generated the `os` extension from the very latest go - and that added some additional code - tengu basically only supports the latest go.  Might be worth a think.

**Comment by d5** [comment]
Regarding the cancellable/timeout context, adding it to the current implementation is not a big deal, but, the only problem is that the current VM implementation has basically a data race on `VM.aborting` member as 2 goroutines will be reading and writing. I tried couple different things (e.g. `select` inside the VM's main for loop, putting time deadline and checking it) to make it cleaner, but, they were way too slower than that the current implementation of simple `bool` checking. I don't know yet, but, there could be a cleaner way to achieve this without losing any running performance.
