### ISSUE TITLE
Concatenate/Append strings

### ISSUE THREAD

**Issue by Bluscream** [d5/tengo#175]
How do I append a string to a variable etc? Like `p := "[" + var + "]"`

**Comment by earncef** [comment]
For your example, exactly as you've done. However, if you're appending string to a non-string and want a string result, you do `p := string(nonStringVar) + "some string"`

**Comment by Bluscream** [comment]
Can you add this to the documentation?

**Comment by d5** [comment]
It's not clearly documented, but, we have [Operators](https://github.com/d5/tengo/blob/master/docs/operators.md) documented.

I thought about supporting `non-string + string = string`, but, the problem that 
1) the other type may define its own `+` with `string`
2) it's not easy to implement universal string concat operation on all types (for example, even if we add string concat operator to all run-time types, it will not work wit custom types)

And, as @earncef said, `string()` function is still available if needed.

**Comment by earncef** [comment]
As of v1.23.0, builtin function `format` is a better way to format strings with non-string objects. It is described in the [Builtins](https://github.com/d5/tengo/blob/master/docs/builtins.md) documentation.
