### ISSUE TITLE
iterator performance

### ISSUE THREAD

**Issue by d5** [d5/tengo#196]
Currently `for-in` statement is implemented by unpacking it into regular `for` statement and a hidden value `:it` ([here](https://github.com/d5/tengo/blob/master/compiler/compiler_for.go#L80)). It works correctly, but, one problem with this approach is that we do lots of type assertions (to `Iterator`) during the iterations: [OpIteratorNext](https://github.com/d5/tengo/blob/master/compiler/compiler_for.go#L80), [OpIteratorKey](https://github.com/d5/tengo/blob/master/runtime/vm.go#L1031), [OpIteratorValue](https://github.com/d5/tengo/blob/master/runtime/vm.go#L1040). We can improve the running performance by either implementing `for-in` statement completely differently, or, somehow removing `Iterator` type assertions. _(We may be able to merge `Iterable` interface to `Object`, but, it doesn't feel quite right to merge `Iterator` and `Object` interface.)_

**Comment by wdvxdr1123** [comment]
I have a idea that implementing `for-in` using a Iterator Stack. It allows us only type assert to `Iterator` in `OpIteratorInit` and remove the hidden value`:it`.
