### ISSUE TITLE
Simplify Calling tengo functions from Go

### ISSUE THREAD

**Issue by Chillance** [d5/tengo#207]
I really like this project and scripting language. I like that has similar Go syntax, and has good speed. Turns to native Go I assume. I noticed tengo doesn't support returning multiple values though, maybe for tengo2?

Now, I noticed that #204 is in tengo2 branch, so I'm guessing it will take a while before it's officially released?

What I was wondering is, would the functionality to call a function in tengo from Go made a bit easier? Say, able to call from the compiled script or something?

Thanks!

**Comment by d5** [comment]
Yeah, we've been working on a new version in `tengo2` branch, but, things have been slow lately. And, one of the changes in the new version is to allow calling Tengo functions (`CompiledFunction`) from Go functions. There are couple of issues we're trying to address (especially around error handling), but, hopefully the new version will be released soon. Thanks!

**Comment by Chillance** [comment]
So, it's not possible to call tengo functions from Go in v1?
