### ISSUE TITLE
Load/Save Bytecode into Compiled

### ISSUE THREAD

**Issue by phrozen** [d5/tengo#214]
Hey, I just found the project and seems great. I could not find a way in the exported code to export the Bytecode and save for later use (ie. Database) and load it again later into a Compiled instance. Is this possible? I think the functionality is there since the standalone interpreter/CLI can already do this by compiling and executing compiled code from file.

**Comment by rbund** [comment]
@phrozen : have a look onto **cli/cli.go**.
Function `CompileOnly()` shows how to compile source to byte code and function `RunCompiled()` loads byte code from a file and executes it.
Hope this helps.

**Comment by phrozen** [comment]
Amazing, exactly what I was looking for, thanks!
