### ISSUE TITLE
Limit script execution time and memory

### ISSUE THREAD

**Issue by phrozen** [d5/tengo#215]
I require to limit both memory usage and execution time of a script in the VM. Memory is kinda already there with MaxAllocs and both string/bytes length, but is kinda lacking a fine control over resource allocation.

Is it possible to support MaxExecutionTime and MaxMemory to the script in the VM?

**Comment by mccolljr** [comment]
What kind of values would we provide to MaxMemory? See [Go Issue #16843](https://github.com/golang/go/issues/16843) for a discussion about defining a max heap size / tracking heap size. Go doesn't seem to have a concrete solution for this, which limits what we can do as a part of the implementation.

**Comment by mccolljr** [comment]
@phrozen did you see my above comment?

**Comment by phrozen** [comment]
Yes, is there a way to kill the VM in mid execution? Maybe not provide a MaxMemory value on creation but being able to track some stats of the runtime would help, to be able to shut it down if necessary. About the time execution limit, would that be feasible?

**Comment by hamstah** [comment]
Hi, Are there any updates on the thinking for this? Particularly the max execution time either in frames or actual time. Without being familiar with the code, it seems that adding some checks in vm run() in the main loop would be doable? I'm happy to work on a patch with some pointers on what's the preferred implementation.

**Comment by d5** [comment]
You can use `VM.Abort` method. Actually `Script.RunContext` uses the same method to abort the VM when the context is cancelled.

**Comment by hamstah** [comment]
@d5 perfect, thanks!

For reference here is an example

```
	ctx, cancel := context.WithTimeout(context.Background(), 5 * time.Millisecond)
	defer cancel()

	if err := fn.RunContext(ctx); err != nil {
		return err
	}
```
