### ISSUE TITLE
Tengo playground example stuck at executing...

### ISSUE THREAD

**Issue by npafitis** [d5/tengo#220]
The Tengo Playground example found in this project's readme seems to stick at executing code.

**Comment by mccolljr** [comment]
@npafitis I just went to the playground from the README link and executed the code successfully, can you post some more details?

**Comment by npafitis** [comment]
@mccolljr Weird, seems to be working perfectly fine now. I tried this from my workplace the first time, is it possible that it was blocked by a firewall.
