### ISSUE TITLE
Method chaining with Go objects

### ISSUE THREAD

**Issue by sibeshkar** [d5/tengo#225]
Hello,

Thank you for creating Tengo.

I wanted to create a program where I define an object and it's methods in pure go, and use them in a tengo script using method chaining (kinda like [jquery](https://www.w3schools.com/jquery/jquery_chaining.asp)). I was wondering if this was possible in tengo, and if yes, then what's the best way to do it. I am aware that I can define custom object types using [this](https://github.com/d5/tengo/blob/master/script/script_custom_test.go) example, but was looking for any pointers as to how define and call custom methods.

Thanks.

**Comment by geseq** [comment]
I don’t think you’ll be able to achieve method chaining like you described with custom objects. The closest you could get is by perhaps using the Callable interface to create a custom object that returns another custom object for the Call method with its own Callable implementation ...

However the syntax would be clunky and not like the method chaining you’re looking for.
