### ISSUE TITLE
variadic does not work

### ISSUE THREAD

**Issue by shnifer** [d5/tengo#227]
Hello! I tried this sample code 
```
variadic := func (a, b, ...c) {
  return [a, b, c]
}
variadic(1, 2, 3, 4)
```

both on playground and my code, and got this error:

```
Parse Error: expected 'IDENT', found '...'
	at (main):1:25 (and 1 more errors)

------------------------
Version: 1.23.0
```

**Comment by shnifer** [comment]
Ohh, I see. Thanks for response )

**Comment by d5** [comment]
Updated tengo playground to 1.24.6. Please let me know if it fixes the issue. Thanks!
