### ISSUE TITLE
skipBlock parameter of Parent function in compiler/symbol_table.go

### ISSUE THREAD

**Issue by summerwinter** [d5/tengo#236]
Hi, I'm trying to study the great Tengo code, and I'm confused with the skipBlock parameter of Parent function in compiler/symbol_table.go. For example,
```
if Event.user_id == 123 {
	ret1 := 123
}
ret2 := 456
```

in above code, both ret1 and ret2 would be treated as GLOBAL variable, based on below Tengo source code(compiler/symbol_table.go), which is not reasonable.

```
// Define adds a new symbol in the current scope.
func (t *SymbolTable) Define(name string) *Symbol {
	symbol := &Symbol{Name: name, Index: t.nextIndex()}
	t.numDefinition++

	if t.Parent(true) == nil {
		symbol.Scope = ScopeGlobal
	} else {
		symbol.Scope = ScopeLocal
	}

	t.store[name] = symbol

	t.updateMaxDefs(symbol.Index + 1)

	return symbol
}

// Parent returns the outer scope of the current symbol table.
func (t *SymbolTable) Parent(skipBlock bool) *SymbolTable {
	if skipBlock && t.block {
		return t.parent.Parent(skipBlock)
	}

	return t.parent
}
```

Could you kindly help explain the usage of skipBlock parameter? Looks like return t.parent directly would work as expected.

**Comment by d5** [comment]
`skipBlock` exists to differentiate function scopes vs block scopes. Blocks do not affect the symbols' scopes. Assuming your example code is outside a function, both `ret1` and `ret2` are global symbols because of that.
