### ISSUE TITLE
Runtime Error: not function: compiled-function

### ISSUE THREAD

**Issue by ozanh** [d5/tengo#246]
Hi,  I had ``Runtime Error: not function: compiled-function`` error with code below.
Here is a simplified example program
https://play.golang.org/p/03n2QoKQGAz
```go
package main

import (
	"github.com/d5/tengo/v2"
	"github.com/d5/tengo/v2/stdlib"
)

func main() {
	src := `
mymodule1 := import("mymodule1")
mymodule2 := import("mymodule2")
`
	script := tengo.NewScript([]byte(src))

	mods := tengo.NewModuleMap()
	mods.AddSourceModule("mymodule1", []byte(`enum := import("enum"); value := func(x) { return enum.value(1,x); }`))
	mods.AddSourceModule("mymodule2", []byte(`mymodule1 := import("mymodule1");`))
	mods.AddMap(stdlib.GetModuleMap(stdlib.AllModuleNames()...))
	script.SetImports(mods)
	compiled, err := script.Compile()
	if err != nil {
		panic(err)
	}
	if err := compiled.Run(); err != nil {
		panic(err)
	}
}
```
When I remove any import from (main) module, error is not raised! I couldn't find the reason but the error code is here https://github.com/d5/tengo/blob/d5b24138d31ce12ba772213de99ea8b05b9ea6d3/vm.go#L720-L728

**Comment by geseq** [comment]
The import is not a function, so you'd want your rewrite your `mymodule1` like this:

```
value := func(x) { enum := import("enum"); return enum.value(1,x); }
```

**Comment by ozanh** [comment]
@geseq in this case this solves the problem, we need a generalized solution to document. Can you explain why it is happening? Of course, my case is different than example code but most of the time I got `Runtime Error: not function: compiled-function`.

I have tried many things to work with source modules as if tengo is like any other standalone scripting languages but I failed too much (probably lack of knowledge). Using builtin modules and using less source modules are only options for me now. Any ideas to work heavily with source modules? When I import a common module (imported by other modules) it eventually gives me this error (removing import of the common module from (main) always solves the problem). Thanks.

**Comment by geseq** [comment]
Source modules expect all of the global variables in the module to be functions, similar to builtin modules or stdlib modules. When you import a module into a global variable within another module, it’s not a function. Hence the error. 

I agree that this can be documented better. I’ll try and work on it.

**Comment by ozanh** [comment]
Thank you @geseq for supporting tengo
