### ISSUE TITLE
builtin function delete()

### ISSUE THREAD

**Issue by ozanh** [d5/tengo#248]
I think there is no builtin `delete` function for maps to delete keys as go has. It can be improved to handle deleting array indices. I need this feature, if it is not planned I can try to implement a builtin delete for Map and Array. What do you think about this?

**Comment by geseq** [comment]
There is a PR for map deletes but I think the author might’ve abandoned it so feel free to create a PR!

**Comment by ozanh** [comment]
PR created for builtin delete #250
