### ISSUE TITLE
Add shebang support (#!)

### ISSUE THREAD

**Issue by breml** [d5/tengo#251]
To use tengo as scripting language in the terminal, support for shebang (`#!`) would be beneficial.

Additional question, what is the proposed file extension for tengo files?

**Comment by ozanh** [comment]
I think file extension is `.tengo` as shown in [cli documentation](https://github.com/d5/tengo/blob/master/docs/tengo-cli.md)

**Comment by d5** [comment]
If the goal is simply to support shebang, it should be implemented in Tengo CLI as a special case, rather than a language-wide comment syntax. Tengo CLI can simply ignore the first line of .tengo file if it starts with `#!`. (https://github.com/d5/tengo/pull/263#issuecomment-605391943)

**Comment by ozanh** [comment]
I can add shebang support if no one is currently working on it. Please let me know.

**Comment by d5** [comment]
No one's working on this as far as I know.

**Comment by ozanh** [comment]
Scanning and skipping BOM bytes and `#!` till the `\n` char with a function can do this job from `cmd/tengo/main.go` using `inputData`. In addition, I think program needs to change the current working directory using inputFile in case file import exists, right? Do I miss anything?

**Comment by d5** [comment]
1. Yeah, maybe we should add a proper handling of BOM, but I think it should be a separate PR.
2. We can simply check if the beginning of the first line is `#!`. If so, we can simply trim it. 
3. Not sure what you want to change with import path?

**Comment by ozanh** [comment]
Tengo modules can have file imports with relative paths, if we don't change the current working dir, can compiler find the imported modules? AFAIK compiler just takes the file name not the path. `os.Chdir()` call with file's dirname would be enough, I think.

**Comment by d5** [comment]
Yeah. We're using `ioutil.ReadFile` to read the files (in tengo main and file module reading code), which will take care of relative path. So... I think we should leave it as is unless we have some edge cases found?

**Comment by ozanh** [comment]
If we do not change the current working dir, a tengo script must use absolute paths to import another module. Also, if a script wants to create a file it may unintentionally create the file where tengo executable is, not in script's dir. I will later create an issue for this after shebang support.
