### ISSUE TITLE
builtin function splice

### ISSUE THREAD

**Issue by ozanh** [d5/tengo#252]
JS `splice` function looks like [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)
```js
let arrDeletedItems = array.splice(start[, deleteCount[, item1[, item2[, ...]]]])
```
I can implement it like this for tengo
```golang
deleted_items := splice(array, start[, delete_count[, item1[, item2[, ...]]]])
```
if `delete_count` is not provided, JS deletes the array items starting from the `start` to the end. If `delete_count` is provided, after deletion (if greater than 0), item1, item2, etc. are inserted to the original array. If `delete_count` is 0 and items are provided then it inserts the items to the array starting from `start` index and nothing deleted from the array. It appends, deletes and inserts with the same function.
What do you think?

**Comment by geseq** [comment]
Sounds good! Are you going to work on an implementation?

**Comment by ozanh** [comment]
Yes I am planning to complete it this week. I have just one question. Should it be a bulitin function or Array method e.g. `Array.splice()` ?

**Comment by geseq** [comment]
A builtin function would be better and keep to the tengo standards

**Comment by ozanh** [comment]
You are right, I need couple of days to finish. Thanks.
