### ISSUE TITLE
is_undefined does not worked for compiled scripts?

### ISSUE THREAD

**Issue by joseph-montanez** [d5/tengo#257]
I am using is_undefined and when I compile the script, it errors out with `Compile Error: unresolved reference 'globalState'`

Tengo Script
``` go
fmt := import ("fmt")
times := import ("times")
rl := import ("rl")

if is_undefined(globalState) {
	fmt.println("globalState undefined")
	globalState := {}
}
```

Compile Script
```go
script := tengo.NewScript([]byte(codeStr))

//-- Load Modules
mods := tengo.NewModuleMap()
mods.AddMap(stdlib.GetModuleMap(stdlib.AllModuleNames()...))
script.SetImports(mods)
//-- Adding this lets the script compile, but the state keeps resetting.
//script.Add("globalState", globalState)

//-- Compile Script
log.Println("compiling " + assetType.Path)
compiledScript, err := script.Compile()
```

Clone and Run Script
```go
script := compiledScript.Clone()
if err := script.Set("globalState", globalState); err != nil {
	//panic(err)
	log.Println(err)
}
if err := script.Run(); err != nil {
	//panic(err)
	log.Println(err)
}
```

All I am trying to do here is create a global state that can live between script runs. So I wanted to pass `SET` a variable that the tengo scripts can read and change. If I `ADD` the variable when compiled the variable is reset every time its cloned. So this is where I was looking at `is_undefined` but that create a compile error.

**Comment by geseq** [comment]
You need to first define the variable "globalState". Something like this:

```go
script := tengo.NewScript([]byte(codeStr))
script.Add("globalState", nil) 
```

**Comment by geseq** [comment]
Ah, I didn't read the part about you trying `Add`. When you say the variable is reset every time it's cloned, do you mean in the new instance, or in the previous cloned instances?

**Comment by geseq** [comment]
At the end of your script run you can do this:
`globalState = script.Get("globalState")`

What you've done with `Set` is fine, but neither `Add` not `Set` transfer the state back into your original variable at the end of the script run. You need to use `Add` before you compile and `Set` as you do now, and then use a `Get` to update the original variable that you're using as your global state.

**Comment by joseph-montanez** [comment]
@geseq I was looking at the wrong call stack so, it does look like the data is carried over, as long as I pull it out and add it back. 

I guess I was expecting `is_undefined` to work variables that don't exist in the VM, rather than variables that exist but are `nil`. Looking over the test cases, it does not seem like it was designed that way and instead only used to check the variable's type to see if its `nil` rather than if its undefined. `is_nil` would have been a better name for it.

**Comment by geseq** [comment]
The `Undefined` type is is more than just `nil`. For instance array index/map key access on `Undefined` returns another `Undefined`.
