### ISSUE TITLE
Proposal to Add Value() to objects.Object

### ISSUE THREAD

**Issue by mdbazuin** [d5/tengo#26]
I was looking into how easy it would be to add an `encoding/json` module.
However when i put a tengo map, like: 
```testMap := {foo: "bar"}```
the output result will be:
```json
{"foo":{"Value": "bar"}}
``` 
Since the Tengo string object contains the Value field, the result would be like the above.

The proposal would be to add another method signature to the objects.Object interface:
```go
type Object interface{
  Value() interface{}
}
```
which would in the case of the Tengo objects return the value as it is saved in the struct

Do you think something like that would be useful or that it would only make the interface to complicated for simple use? 

Unless there are other plans for making a Map Object more accessible in Go?
In the mean time it should also be possible to just do type conversion and work with that, i'll give that a shot too

**Comment by mdbazuin** [comment]
This is what i came up with so far. I can add this to the 
I can also convert this into two functions in `objects.conversion.go` called `ToMap` and `ToArray`
```go
func convertToInterface(o objects.Object) (interface{}, error) {
	var res interface{}
	var ok bool
	switch o.(type) {
	case *objects.Int:
		res, ok = objects.ToInt(o)
		if !ok {
			return nil, objects.ErrInvalidTypeConversion
		}
	case *objects.String:
		res, ok = objects.ToString(o)
		if !ok {
			return nil, objects.ErrInvalidTypeConversion
		}
	case *objects.Float:
		res, ok = objects.ToFloat64(o)
		if !ok {
			return nil, objects.ErrInvalidTypeConversion
		}
	case *objects.Bool:
		res, ok = objects.ToBool(o)
		if !ok {
			return nil, objects.ErrInvalidTypeConversion
		}
	case *objects.Char:
		res, ok = objects.ToRune(o)
		if !ok {
			return nil, objects.ErrInvalidTypeConversion
		}
	case *objects.Bytes:
		res, ok = objects.ToByteSlice(o)
		if !ok {
			return nil, objects.ErrInvalidTypeConversion
		}
	case *objects.Array:
		values := o.(*objects.Array).Value
		resSlice := make([]interface{}, len(values))
		for i, v := range values {
			nestedRes, err := convertToInterface(v)
			if err != nil {
				return nil, err
			}
			resSlice[i] = nestedRes
		}
		res = resSlice
	case *objects.Map:
		mapValue := o.(*objects.Map).Value
		resMap := make(map[string]interface{})
		for key, v := range mapValue {
			nestedRes, err := convertToInterface(v)
			if err != nil {
				return nil, err
			}
			resMap[key] = nestedRes
		}
		res = resMap
	}
	return res, nil
}
```

**Comment by mdbazuin** [comment]
Oh i completely missed those functions haha.

I did read that you want to focus on the other things before a stdlib.

It also makes sense that you only want to include methods that are used by the VM to the object interface

Thanks for the quick response!

**Comment by d5** [comment]
This is great! Can you create a PR here? Btw, I think they should be builtin functions (instead of a module). Something like `to_json` and `from_json`.

**Comment by mdbazuin** [comment]
Awesome! Could you create a new issue for the json stuff and assign it to me? As  the topic of this issue isn't that relevant to the json part haha. I'll work on it tomorrow as i was just about to head to bed.

I'll rewrite it to the `to_json` and `from_json` builtin functions

**Comment by mdbazuin** [comment]
#29 
Created a PR for `to_json` and `from_json`

Also fixes a bug in `scripts/conversion.go`

**Comment by d5** [comment]
Merged your PR. Thanks for the help @mdbazuin !!
