### ISSUE TITLE
go get github.com/d5/tengo/v2 doesn't work with Go v1.14 on MacOS.

### ISSUE THREAD

**Issue by AllenDang** [d5/tengo#261]
package github.com/d5/tengo/v2: cannot find package "github.com/d5/tengo/v2" in any of:
	/usr/local/Cellar/go/1.14/libexec/src/github.com/d5/tengo/v2 (from $GOROOT)
	/Users/allendang/Documents/Gocode/src/github.com/d5/tengo/v2 (from $GOPATH)

And if I "go get github.com/d5/tengo", it could work. 

But below example code cannot run.

```
fmt := import("fmt")

each := func(seq, fn) {
    for x in seq { fn(x) }
}

sum := func(init, seq) {
    each(seq, func(x) { init += x })
    return init
}

fmt.println(sum(0, [1, 2, 3]))   // "6"
fmt.println(sum("", [1, 2, 3]))  // "123"
```

Error message is Compile Error: module 'fmt' not found

What happened?

**Comment by infinytum** [comment]
Can you post the code of the main.go file used to run the script? You need to add the stdlib modules to the Script like this:

```go
script := tengo.NewScript([]byte(src))
script.SetImports(stdlib.GetModuleMap(stdlib.AllModuleNames()...))
```

or just the fmt module
```go
script := tengo.NewScript([]byte(src))
script.SetImports(stdlib.GetModuleMap("fmt"))
```

**Comment by AllenDang** [comment]
@infinytum I cannot go get this package according to the doc. That's the major issue.

**Comment by infinytum** [comment]
Are you working inside a go modules project?

If not, just use 'go get github.com/d5/tengo'
