### ISSUE TITLE
Is this project still being actively developed?

### ISSUE THREAD

**Issue by T2RKUS** [d5/tengo#264]
Hello, does the tengo2 branch work? What is currently halting progress?

**Comment by d5** [comment]
It's being maintained but not in an active development. `tengo2` branch was used to work on more experimental features a while ago, but I recently merged some of those features into `master` and up the version to `v2.x`. I just deleted `tengo2` branch.

**Comment by T2RKUS** [comment]
That’s a shame... the tengo2 branch had a better folder structure, of it worked I was going to fork it. Did you merge the feature that allows you to directly call a tengo function from go code instead of the work around used in go-fsm?

**Comment by tmclane** [comment]
So are you considering the project dead?   Or just that v2 matured enough to merge into master?

**Comment by d5** [comment]
Well. We still maintain the code. There hasn't been much of "new" features for sure, but I'm not sure if that makes the project dead.

**Comment by tmclane** [comment]
Fair enough!  I was just confused with the other question. I was hoping you hadn't abandoned it completely!

**Comment by d5** [comment]
Been super busy and couldn't find a time to work on Tengo, but I still review PRs and work on bug fixes.
