### ISSUE TITLE
spread support

### ISSUE THREAD

**Issue by ozanh** [d5/tengo#265]
Hi, there was spread syntax support for variadic function calls and arrays in tengo2 branch, which was implemented by @mccolljr #190  . Is there a reason not to implement it in master branch with or without explosions?

**Comment by tmclane** [comment]
Unless I am mistaken that was merged in to v2.

**Comment by tmclane** [comment]
Ok after further digging in to the Git history I can see it was merged into tengo2 branch which doesn't appear to have become the new master.

**Comment by d5** [comment]
I'm open to revisit the feature if anyone wants to try implementing it again, but I didn't merge it to master last time because I found some edge cases that were not covered by the implementation. I really liked @mccolljr 's implementation, but I didn't have more time to identify and/or fix those issues. I figured Tengo should be simple and fast, even if it's missing some nice features. I'm not against the idea of adding new features, but only if they're complete and do not affect the running performance.

**Comment by ozanh** [comment]
@d5 could you please re-open this issue again? I will soon complete my spread implementation. I can share benchmark results and some details here before a PR. My spread implementation will cover spread in arrays, maps and function calls like JS.

**Comment by ozanh** [comment]
I finally added some tests (vm, compiler, parser tests) to the new implementation and a fibonacci benchmark test to see how it affects function call performance. Tests are successful but there may be edge cases that I haven't tested for. Implementation is very similar to ES6 spread operator with little differences. For now, any expression after ellipsis is accepted within array, map, call expressions.
These are from directly vm tests

```go
expectRun(t, `out = [...["a", "b", "c"]]`, nil, ARR{"a", "b", "c"})

expectRun(t, `out = [...["a", "b"], "c"]`, nil, ARR{"a", "b", "c"})

expectRun(t, `
	f1 := func(...a){
		return [3, ...a]
	}
	f2 := func(a, ...b) {
		return f1(...[a, ...b])
	}
	out = f2(...[1, 2])
	`, nil, ARR{3, 1, 2})

expectRun(t, `out = {k2: "v2", ...{k1: "v1"}, ...{k3: 3}}`, nil, k1": "v1", "k2": "v2", "k3": 3})
```
Note: immutable arrays and immutable maps are also spread. Unlike JS, function calls accepts only 1 spread expression which can be the last argument like Go.

I had to introduce a new OpCode which is `OpSpread`. In vm `OpArray OpMap OpCall` sections are updated. As @d5 's performance concerns were noted; New `OpCall` first lines look like this;
```go
func (v *VM) run() {
	var spreadPtr Object = &spreadType{}

...

    case parser.OpCall:
	numArgs := int(v.curInsts[v.ip+1])
	v.ip++

	if numArgs > 0 && v.stack[v.sp-1] == spreadPtr { // spread last argument if true
```
Considering function calls, I thought the most performant way to implement it was this way by just adding an if block with fast comparison without type switches or looping over stack to identify last argument is spread.
I benchmarked fibonacci(35) and the results are below;
```
name    old time/op    new time/op    delta
Fib        3.25s ± 0%     3.27s ± 1%  +0.58%  (p=0.000 n=8+9)
FibTC1     3.72s ± 0%     3.75s ± 0%  +0.60%  (p=0.000 n=10+9)
FibTC2    51.6µs ± 0%    54.2µs ± 1%  +5.07%  (p=0.000 n=10+10)

name    old alloc/op   new alloc/op   delta
Fib        313MB ± 0%     313MB ± 0%    ~     (p=0.171 n=10+10)
FibTC1     358MB ± 0%     358MB ± 0%  +0.00%  (p=0.030 n=10+10)
FibTC2     126kB ± 0%     126kB ± 0%    ~     (p=0.382 n=10+10)

name    old allocs/op  new allocs/op  delta
Fib        39.1M ± 0%     39.1M ± 0%  -0.00%  (p=0.003 n=10+10)
FibTC1     44.8M ± 0%     44.8M ± 0%    ~     (p=0.108 n=10+10)
FibTC2       462 ± 0%       462 ± 0%    ~     (all equal)
```
The new implementation is `0.6%` - `1%` slower due to implementation.

Tengo objects are the same and interface didn't change. I introduced a new exported interface 
```go
type Spreader interface {
	Spread(parser.SpreadIn) (Object, error)
}
```
Any foreign type implementing this interface can be spread within maps, arrays, calls.

**Comment by d5** [comment]
I can take a look if you open a PR for this.
