### ISSUE TITLE
Is it possible to add a reference to another tengo script?

### ISSUE THREAD

**Issue by idoall** [d5/tengo#279]
The file I use tengo script has 50kb, and multiple tengo scripts have public methods. Can I keep the public method as a tengo script, and then import the public tengo script at execution time

**Comment by ozanh** [comment]
As far as I understood, tengo source modules are not shared between different scripts, they are all compiled to one bytecode with main code. Do you heavily use Tengo source modules or pure Go modules?

**Comment by idoall** [comment]
I use tengo module a lot, tengo file is 50kb+, and there are many repeated methods in it. It is more convenient to use the reference combination between tengo modules before compilation

**Comment by ozanh** [comment]
Do you run 50KB file with tengo cli or do you embed script in an application? If you don't run thousands of scripts 50KB is not a big deal or do you run scripts in a microchip :flushed: ?

**Comment by idoall** [comment]
About 20 tengo scripts of 50kb are running in an application
There is a general method. In the debugging stage, it is often modified, which is not very convenient

**Comment by ozanh** [comment]
What about running common utility/helper functions in a separate VM and scripts talk to each other?

**Comment by d5** [comment]
I'm not sure if I understood correctly, but can you put shared functions in a separate source, and load it as SourceModule from your other scripts?

**Comment by d5** [comment]
I think it's easier if you share some of your code. I'm not quite sure what you're trying to do here.
