### ISSUE TITLE
Nested imports fail

### ISSUE THREAD

**Issue by maichmueller** [d5/tengo#281]
I have three tengo files `uno.tengo`
```
due := import(`due`)

due.funcy(1)
```
the second file `due.tengo`,
```
tre := import(`tre`)


funcy := func(a) {
  return tre.fun(a)
}

due := {
  funcy: funcy
}
export due
```
and the third  `tre.tengo`
```
fun := func(a) {
  return a
}

tre := {
  fun: fun
}
export tre
```

All files are in the same folder. Invoking `tengo uno.tengo` within the same folder throws the error:

> Compile Error: module 'tre' not found
        at due.tengo:1:8

So it seems nested imports don't work.

**Comment by ozanh** [comment]
Hi, it looks like there is a small bug, @d5 @geseq Can following patch fix this? Apparently, `allowFileImport` is not set for child compilers.
```patch
diff --git a/compiler.go b/compiler.go
index eb686ed..4d3dd60 100644
--- a/compiler.go
+++ b/compiler.go
@@ -1086,6 +1086,7 @@ func (c *Compiler) fork(
        child := NewCompiler(file, symbolTable, nil, c.modules, c.trace)
        child.modulePath = modulePath // module file path
        child.parent = c              // parent to set to current compiler
+       child.allowFileImport = c.allowFileImport
        return child
 }

```

**Comment by d5** [comment]
Yes, please open PR with your change. Thanks @ozanh
