### ISSUE TITLE
Can tengo module support changing script suffix？

### ISSUE THREAD

**Issue by idoall** [d5/tengo#286]
vm.Compile() Error	{"error": "[uno.mshk]Compile Error: module file read error: open due.tengo: no such file or directory\n\tat (main):1:8"}

vm.Compile() Error	{"error": "[due.mshk]Compile Error: module file read error: open tre.tengo: no such file or directory\n\tat (main):1:8"}

**Comment by ozanh** [comment]
Do you want to use another file extension instead of `.tengo` :scream: :open_mouth: ?  :-1:

**Comment by idoall** [comment]
yes, file extension ".mshk"

**Comment by idoall** [comment]
Tengo module file extension, can you make dynamic configuration?

**Comment by d5** [comment]
Yeah, we should probably update the Compiler to take other extensions. `.tengo` can be appended only if the given module does not have any file extensions.

```golang
import("one") // one.tengo
import("one.tengo") // one.tengo
import("one.two") // one.two
```

**Comment by ozanh** [comment]
What if somebody has `module.xyz.tengo` file already and imports it like `import("module.xyz")` ?

**Comment by idoall** [comment]
> module.xyz.tengo

```
import("module.xyz.tengo")
```

**Comment by d5** [comment]
Yeah, I think the general rule can be:

> `.tengo` is appended **only if** the name does not include any file extensions.

Users can still use the full file names if necessary.

**Comment by ozanh** [comment]
I know that is an option @idoall but there are already running scripts and compiler needs to check file existence twice every time when path does not exist. I don't often see different extensions with python, js, etc.

**Comment by d5** [comment]
We don't have to pre-check if the file exists or not. We simply check the file name and append `.tengo` if necessary but purely based on names. Maybe I'm missing something?

**Comment by ozanh** [comment]
@d5 tengo cli runs bytecode and source file by checking extension. We need add a cli switch or bytecode file extension to distinguish different file types to run.

**Comment by d5** [comment]
Aha. I forgot about it. But I guess this is for `import()` inside the script file. We can keep the current CLI logic to determine bytecode vs source file as is?

**Comment by ozanh** [comment]
@d5 Let's wait for a week to see other feedbacks, if this is not urgent. I can create a PR but @idoall is this an urgent issue?

**Comment by idoall** [comment]
It's OK to wait a week

@ozanh

**Comment by ozanh** [comment]
@idoall It's been more than a week but my priorities has changed so my next PR will address this issue when I have time, sorry.

**Comment by idoall** [comment]
OK, thank you. Please

**Comment by KEINOS** [comment]
I would like to PR this issue if I may.

My idea is to implement `tengo.Compiler.SetImportExt(extension string)` method.
This method will set an extra custom extension to search. This will take effect only if `allowFileImport` is `true`.

```go
func main() {
...
    c := tengo.NewCompiler(srcFile, nil, nil, modules, nil)
    c.EnableFileImport(true)
    c.SetImportDir(filepath.Dir(pathFileSource))
    c.SetImportExt(".mshk") // It will search `<module_name>.tengo` and `<module_name>.mshk`
...
}
```
