### ISSUE TITLE
How to use import()？

### ISSUE THREAD

**Issue by idoall** [d5/tengo#287]
How to use it? I have the following error here

```
vm.Compile() Error	{"error": "[uno.tengo]Compile Error: module file read error: open due.tengo: no such file or directory\n\tat (main):1:8"
```

Do need to reconfigure the directory separately？

**Comment by ozanh** [comment]
Can you share your dirs+files structure? Note: Relative file import support has not been implemented yet.

**Comment by idoall** [comment]
```
/Users/lion/my_project/_golang/cryptotrader/data/mshk git:(master) ✗ >tree
.
|____uno.tengo
|____tre.tengo
|____due.tengo
```

**Comment by ozanh** [comment]
If you are using tengo CLI, you need to use absolute import paths OR process current working directory must be same with where your scripts are if `*.tengo` files include relative import paths (using `cd` command).
If you are running scripts in your Go application, use `os.Chdir()` before script compilation and change later OR use absolute import paths.
New release will solve these issues though.

**Comment by idoall** [comment]
ok,thx
