### ISSUE TITLE
panic: interface conversion: tengo.Object is *tengo.CompiledFunction, not *tengo.String

### ISSUE THREAD

**Issue by DerThorsten** [d5/tengo#289]
Having two source modules where the one uses the others gives panic.
```
package main

import (
	"fmt"

	"github.com/d5/tengo/v2"
	"github.com/d5/tengo/v2/stdlib"
)

func main() {

	script := tengo.NewScript([]byte(`
		module_a := import("module_a")
		module_b := import("module_b")
		module_b()
	`))
	mods := stdlib.GetModuleMap("json", "fmt", "math", "times")

	mods.AddSourceModule("module_a", []byte(`
		fubar := func(arr, low, n) {
		    i := low + 1
		    for i < n + 1 {
		    }
		}

		module_a := {
		    "fo": func(){}
		}

		export module_a
	`))

	mods.AddSourceModule("module_b", []byte(
		`export func(){
			module_a := import("module_a")
		}
	`))
	script.SetImports(mods)

	compiledFunc, err := script.Compile()
	if err != nil {
		panic(err)
	}

	fmt.Println("RUN")
	err = compiledFunc.Run()
	if err != nil {
		panic(err)
	}
}
```

**Comment by ozanh** [comment]
@DerThorsten I still don't know all the mechanics of tengo but I can say that I do not use global variables within source modules, they are not like (main) module, they look like they are designed to hold only compiled functions. My best practice is to do something like this;
```go
export  {
  fun1: func() {...},
  fun2: func() {...}
}
```

**Comment by ozanh** [comment]
I realized that when you change the order in `module_a`, behavior changes. Following module runs without a problem. This is a bug !
```go
        module_a := {
		"fo": func(){}
	}

	fubar := func(arr, low, n) {
			i := low + 1
			for i < n + 1 {
			}
		}

       export module_a
```

**Comment by ozanh** [comment]
@d5 Could you please check this patch? I think it solves the problem. Since same compiled function is processed more than one, constants become wrong.
```patch
diff --git a/bytecode.go b/bytecode.go
index cfd0d0b..39a1e20 100644
--- a/bytecode.go
+++ b/bytecode.go
@@ -169,9 +169,14 @@ func (b *Bytecode) RemoveDuplicates() {
 	// main function
 	updateConstIndexes(b.MainFunction.Instructions, indexMap)
 	// other compiled functions in constants
+	addr := make(map[*CompiledFunction]bool)
 	for _, c := range b.Constants {
 		switch c := c.(type) {
 		case *CompiledFunction:
+			if addr[c] {
+				continue
+			}
+			addr[c] = true
 			updateConstIndexes(c.Instructions, indexMap)
 		}
 	}
```

**Comment by d5** [comment]
Yeah that's a good fix. Let me check a couple of other things.

**Comment by d5** [comment]
What I'm not entirely sure about is de-duping CompiledFunction objects in the main `for` loop of the function. 

```golang
	for curIdx, c := range b.Constants {
		switch c := c.(type) {
		case *CompiledFunction:
			if newIdx, ok := fns[c]; ok {
				indexMap[curIdx] = newIdx
			} else {
				newIdx = len(deduped)
				fns[c] = newIdx
				indexMap[curIdx] = newIdx
				deduped = append(deduped, c)
			}
			// indexMap[curIdx] = len(deduped)
			// deduped = append(deduped, c)
		case *ImmutableMap:
			modName := inferModuleName(c)
			newIdx, ok := immutableMaps[modName]
			if modName != "" && ok {
				indexMap[curIdx] = newIdx
			} else {
				newIdx = len(deduped)
				immutableMaps[modName] = newIdx
				indexMap[curIdx] = newIdx
				deduped = append(deduped, c)
```

Above is the code I just wrote to explain what it was supposed to be. I'm trying to remember why I couldn't de-dupe CompiledFunction objects (pointers) originally. I guess there were some reasons.

**Comment by DerThorsten** [comment]
> @DerThorsten I still don't know all the mechanics of tengo but I can say that I do not use global variables within source modules, they are not like (main) module, they look like they are designed to hold only compiled functions. My best practice is to do something like this;
> 
> ```go
> export  {
>   fun1: func() {...},
>   fun2: func() {...}
> }
> ```

how can I then have some impl. detail I do not want to export in a reusable fashion ( a function which is not exported but used within the implementation of other functions?)
