### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by Kunderao** [d5/tengo#296]
When importing, what is the difference between the two examples below? If you leave out v2, will it use the latest now .. as in v.2.5.0 etc? Thank you.

	"github.com/d5/tengo/v2"
	"github.com/d5/tengo/v2/stdlib"

and 

	"github.com/d5/tengo/"
	"github.com/d5/tengo/stdlib"

**Comment by ozanh** [comment]
Hi, when you run `go get github.com/d5/tengo` it gets and pins latest version 1 tag which is `1.24.8` for tengo.
If a module has version 2, 3, etc. you need to add `/v2 /v3 etc.` to use correct version.
Please read https://blog.golang.org/using-go-modules

**Comment by Kunderao** [comment]
I did a go get github.com/d5/tengo and worked fine but 
go get github.com/d5/tengo/v2 but met with the following error:

c:\gopath\src
λ go get github.com/d5/tengo/v2
package github.com/d5/tengo/v2: cannot find package "github.com/d5/tengo/v2" in any of:
        c:\go\src\github.com\d5\tengo\v2 (from $GOROOT)
        c:\gopath\src\github.com\d5\tengo\v2 (from $GOPATH)

c:\gopath\src
λ go get github.com/d5/tengo

c:\gopath\src
λ

**Comment by ozanh** [comment]
What is your go version? Go1.14 works good with modules. Did you run `go mod init` before running `go get ...` in that directory. Try also setting `GO111MODULE=on` env. var.

**Comment by Kunderao** [comment]
afte doing a c:\gopath\src
λ go mod init
go: creating new go.mod: module .

I seem to be getting what is expected:

c:\gopath\src
λ go get github.com/d5/tengo/v2
go: downloading github.com/d5/tengo/v2 v2.5.0
go: github.com/d5/tengo/v2 upgrade => v2.5.0

**Comment by Kunderao** [comment]
module .

go 1.14

require (
	github.com/d5/tengo/v2 v2.5.0 // indirect
)

I setup go.mod file with the above content in Intellij and all is good.
Thank you for the introducing me to the "modules" methodology.
