### ISSUE TITLE
Symbol Table and Closure

### ISSUE THREAD

**Issue by ozanh** [d5/tengo#317]
Hi,

I encountered following behavior at v2.6
```go
f := undefined
if true {
    a := 10
    f = func() {
        a = 20
    }
}
b := 5
f()
fmt := import("fmt")
fmt.println(b)
```
Output
```
20
```
Expected
```
5
```
Symbol table is forked before If statement and symbols next index is reset to the state before forking after If statement finished in compiler, because of that variable `a` and variable  `b` has same symbol index and captured variable in `f` refers to wrong variable. What do you think?

**Comment by d5** [comment]
Yeah, we should fix this. Feel free to open a PR if you have a fix. Thanks.

**Comment by ozanh** [comment]
My quick solution is like this with my custom Tengo implementation in Compiler;
```go
case *parser.IfStmt:
	// open new symbol table for the statement
	c.symbolTable = c.symbolTable.Fork(true)
	defer func() {
		// increment num of definitions because it is safer if a free variable is captured in block and a new
		// variable with same index is created outside of block although we allocate more for locals.
		// This is different than Tengo.
		numDef := c.symbolTable.NumDefinition()
		c.symbolTable = c.symbolTable.Parent(false)
		c.symbolTable.IncrNumDefinition(numDef)
	}()
...
``` 
This. wastes variables defined in blocks but safer. I haven't found a better idea yet. If this fix is OK, I can issue a PR later.

**Comment by d5** [comment]
If I understand this correctly, this is an issue with global symbols, right? `a` gets index of `2` inside `if` block. Then `b` also gets index of `2` outside `if` block.

**Comment by ozanh** [comment]
Yes, they share the same index and `OpGetLocalPtr` points to same stack array index and this becomes a problem.
In my custom Tengo implementation, I have changed what I posted earlier. Now I am testing it and not 100% sure but it looks it is working perfectly.
Let me summarize what I have done;
- I track each `Free` symbol  by keeping a link between original and free symbol.
- I skip the symbol indexes which are used as free variables, in outer scope.
- I mark the compiled functions which change the free variable content (e.g. I call this `PromoteLocals`)
- In VM side, if a compiled function's `PromoteLocals` is true, in `OpCall` I copy compiled function local variables to new slice instead of using stack directly.

This required too much effort but with the help of this free variables can be used safely.
Let me know if my approach is good.

**Comment by d5** [comment]
Hmm. I think a cleaner solution could be making `a` a local symbol. `a` is not supposed to be accessible outside `if` block anyway, right?

**Comment by ozanh** [comment]
`a` is a block variable and must be invisibe in outer scopes. This bug affects both local and global variables whether `if block` is in a compiled function. Other problem is local variables referenced as a free variable in functions can point to a stack index which is not used anymore after function return.

**Comment by d5** [comment]
Can you give me an example code with local variables?

**Comment by d5** [comment]
https://github.com/d5/tengo/pull/318 @ozanh

**Comment by ozanh** [comment]
I didn't test the code but it looks like it fixes this problem. Quick fix thanks :+1: 
I realized that the other issue I mentioned is not related with Tengo, it is my mistake because it is related with my implementation sorry about that, I don't use pointers as objects because of that free variables point to the variables on locals array and I changed lots of things :worried:
