### ISSUE TITLE
QUESTION: file extension for Tengo script

### ISSUE THREAD

**Issue by damiva** [d5/tengo#332]
I would like to use Tengo for plugins scripting for my project.
Have you decided about file extension for Tengo script?
If no, i have tow suggestions:
**.tng** - consonant letters from **T**E**NG**O
**.xgo** - **X** is roman ten + **GO** (also it hints to GO lang)

Additionaly I would like to use IMPORT from files, BUT: can I restrict the use of files only within the selected directory?

**Comment by geseq** [comment]
Tengo uses `.tengo` as the file extension for the files. It's descriptive and clear and I think better than 3 letter extensions that are hard to keep track of.

**Comment by damiva** [comment]
thanks
