### ISSUE TITLE
additional builtin libs

### ISSUE THREAD

**Issue by damiva** [d5/tengo#333]
I would like to use tengo for my plroject (http server) as plugin lang.
I am writing few additional builtin modules:
- httpserver - some request info and rsponse functions (from go http server)
- httpclient - some get, post, etc functions
- url - for working with urls (some functionality of go's net/url)

Are they already realised by somebody?
If no, I can share it when done, tell me how.

**Comment by geseq** [comment]
yes, please feel free to share them

**Comment by damiva** [comment]
ok
