### ISSUE TITLE
Compare String

### ISSUE THREAD

**Issue by afzalabbasi** [d5/tengo#334]
hey Every one
Is there any way to compare the string using tengo ?

**Comment by d5** [comment]
You mean `"abc" == "abc"`?

**Comment by afzalabbasi** [comment]
@d5 yes if the script input is abc and the variables thats we are added using script.add like script.add(a) and so on how i compare input value of script and the variables

**Comment by geseq** [comment]
script.add() defines a variable named after the first argument. Use `==` to compare that variables with any others.

**Comment by afzalabbasi** [comment]
@d5 i have this type of code 
script := tengo.NewScript([]byte("have_fever==true&&have_cough==true"))
script.Add("have_fever","true")
script.Add("have_cough","true")
now can you please help me how i compare the script value and the variables that i was added
Thanks

**Comment by geseq** [comment]
`have_fever == have_cough`

**Comment by geseq** [comment]
Not entirely sure what you’re doing there though. Are you trying to use true as a string or bool?
