### ISSUE TITLE
SSL cert for api.tengolang.com is revoked, playground not working

### ISSUE THREAD

**Issue by polarweasel** [d5/tengo#367]
The playground isn't working for me (macOS 12.2, Safari current version, Chrome current version), and I believe it's due to the API site's SSL cert being revoked.

https://decoder.link/sslchecker/api.tengolang.com/443

**Comment by d5** [comment]
Thanks for reporting. Just fixed and re-deployed the server. Let me know if it works for you. @polarweasel

**Comment by polarweasel** [comment]
Works now! Thanks for the quick fix!
