### ISSUE TITLE
Help me understand VM recursion

### ISSUE THREAD

**Issue by moisespsena** [d5/tengo#369]
Hello!

I am implementing the keyword arguments, but have problem with recursion. I would like to better understand recursiveness at this point.
Thanks!

https://github.com/d5/tengo/blob/0afdfdeb2fbd39a9760e01e80d297df87b2457a6/vm.go#L602-L613

**Comment by geseq** [comment]
So this is a case to check and handle tail call recursion. If we’re trying to call the same function as the one we’re in, we just check that the immediate next step is a return, in which case it’s a tail call. 

If that is the case we update the stack pointer and instruction pointer to run through that function again.

**Comment by moisespsena** [comment]
Thans!
