### ISSUE TITLE
How to solve precision problem in tengo?

### ISSUE THREAD

**Issue by yayakoBlessing** [d5/tengo#379]
Hi,  thanks for such a great project!

How to solve precision problem in tengo?
```go
json := import("json")
fmt := import("fmt")


base_info := bytes(`{
        "1":7075984636689534001,
        "2":7075984636689534002
}`)
m := json.decode(base_info)
fmt.println(m[1])
```

result: 7075984636689534000

**Comment by chkim-dev** [comment]
1. make fixed precision code in golang ( use math/big package )
2. make tengo user module ( like fmt, json )
3. import in tengo code

**Comment by geseq** [comment]
I think this might be due to the Go json package parsing numbers as floats. I’m not sure you can do anything other than write a custom parser for your use case

**Comment by yayakoBlessing** [comment]
Thanks for replying. Does Tengo support for custom parsers? Or should I realize it in another way.

**Comment by geseq** [comment]
Tengo’s json parsing is built off of Go’s but yes you can fairly easily modify it and create your own json library. This might help you get started:

https://github.com/d5/tengo/blob/f90d433d21a3d9ae2349661cc7e68a2c27e826cb/stdlib/json/decode.go#L210

**Comment by yayakoBlessing** [comment]
Thanks, help me a lot!
