### ISSUE TITLE
Runtime panic on self assignment 

### ISSUE THREAD

**Issue by beoran** [d5/tengo#386]
The following Tengo script panics at run time:

a := a.foo

This likely because the compiler wrongly considers a to be defined after the := . A should only be considered defined in the next statement.

**Comment by geseq** [comment]
Right, this is a problem, but I'm not sure your solution would work. It would break recursive functions.

**Comment by beoran** [comment]
For a func block, an exception can be made to the rule I propose that the variable is defined inside there.
