### ISSUE TITLE
Is Tengo production-ready?

### ISSUE THREAD

**Issue by matwachich** [d5/tengo#450]
Hello,
I wanted to know if you think that Tengo is production ready? Do you use it in some critical/commercial software?

Thanks :)

**Comment by geseq** [comment]
Tengo is an open source project with all the caveats that come with one. You’d have to evaluate its suitability and production readiness for your use case yourself.


That said, I have used tengo in production for data pipelines in the past and there’s at least one popular open source project  that uses tengo as a dependency: https://github.com/thrasher-corp/gocryptotrader

YMMV
