### ISSUE TITLE
Make map iterating predictable (either ordered or as inserted)

### ISSUE THREAD

**Issue by matwachich** [d5/tengo#67]

**Comment by d5** [comment]
Can you tell me more about your use cases? Basically Map iterator does not guarantee any ordering just like most other programming languages.

**Comment by d5** [comment]
Definitely possible but as you can see that pre-sorting is an extra overhead. So I’d rather let user to sort the keys and iterate on sorted keys manually if that’s needed, and, keep the current map iterator not sorted. Remember the iteratir (which is implemented using Go map iterator) is not predictable but is consistent.
