### ISSUE TITLE
reflection / host communication

### ISSUE THREAD

**Issue by glycerine** [d5/tengo#8]
First off, tengo looks really great. Thanks for making it!

For using tengo as a scripting language, is it possible to have the host program inject variables or functions into the script namespace for the script to use?

Along these lines, Alan Donovan on the Go team has done some nice reflection work for starlark-go on the wip-stargo branch. Any Go library can be called from script in this manner, as long as bindings have been compiled in.

https://github.com/google/starlark-go/tree/wip-stargo

Since it is 3-clause BSD licensed, good ideas there could be borrowed.

**Comment by d5** [comment]
Thanks for the compliment and reflection link. I will definitely take a look. 

To answer your question. You can definitely inject objects/functions. There are multiple ways to do this, but, probably the easiest is to use `script.Variable`. 

```golang
import (
	"errors"
	"fmt"

	"github.com/d5/tengo/compiler/token"
	"github.com/d5/tengo/objects"
	"github.com/d5/tengo/script"
)

type Counter struct {
	value int64
}

func (o *Counter) TypeName() string {
	return "counter"
}

func (o *Counter) String() string {
	return fmt.Sprintf("Counter(%d)", o.value)
}

func (o *Counter) BinaryOp(op token.Token, rhs objects.Object) (objects.Object, error) {
	switch rhs := rhs.(type) {
	case *Counter:
		switch op {
		case token.Add:
			return &Counter{value: o.value + rhs.value}, nil
		case token.Sub:
			return &Counter{value: o.value - rhs.value}, nil
		}
	case *objects.Int:
		switch op {
		case token.Add:
			return &Counter{value: o.value + rhs.Value}, nil
		case token.Sub:
			return &Counter{value: o.value - rhs.Value}, nil
		}
	}

	return nil, errors.New("invalid operator")
}

func (o *Counter) IsFalsy() bool {
	return o.value == 0
}

func (o *Counter) Equals(t objects.Object) bool {
	if tc, ok := t.(*Counter); ok {
		return o.value == tc.value
	}

	return false
}

func (o *Counter) Copy() objects.Object {
	return &Counter{value: o.value}
}

func (o *Counter) Call(args ...objects.Object) (objects.Object, error) {
	return &objects.Int{Value: o.value}, nil
}

var code = []byte(`
arr := [1, 2, 3, 4]
for x in arr {
	c1 += x
}
out := c1()`)

func main() {
	s := script.New(code)

	// define variable 'c1'
	_ = s.Add("c1", &Counter{value: 5})

	// compile the source
	c, err := s.Run()
	if err != nil {
		panic(err)
	}

	// retrieve value of 'out'
	out := c.Get("out")
	fmt.Println(out.Int()) // prints "15" ( = 5 + (1 + 2 + 3 + 4) )
}
```

This example (from README) shows you how to make your own data type by implementing `objects.Object` interface. `Counter` struct also implements `objects.Callable` interface which makes it work like a function in the script. Other than that, putting some values to the script is just a matter of calling `Script.Add()` function (before `Script.Compile()` or `Script.Run()` call). I added the concept of modules yesterday, and, it's another way of putting things in the script. But I guess it's not what you were looking for.

Hope this helps.
