### ISSUE TITLE
Line Number Info when compiled.Run() has error

### ISSUE THREAD

**Issue by kcsampson** [d5/tengo#93]
Would be nice if the error returned by c.Run() would at least give the line number of the script where the error occurred.  A stack-trace would even be nicer in case there was some recursion, or user defined function call.

```	
if c, err := s.Compile(); err != nil {
	t.Errorf("compile error=%s",err )
} else {
	if err := c.Run(); err != nil {
		t.Errorf("error %s",err)
	}
}
```

**Comment by d5** [comment]
This will be fixed with #103. /cc @kcsampson (no stack trace yet)
